//! Derived states: tuần không, vượng suy, trường sinh. FR-CORE-004.

use crate::ganzhi::{Can, Chi, NguHanh};
use crate::relations::{ngu_hanh_of_can, ngu_hanh_of_chi};
use serde::{Deserialize, Serialize};

/// Empty branches for a day pillar (tuan khong).
/// Closed form: {(z - c + 10) % 12, (z - c + 11) % 12} on chi indices.
pub fn tuan_khong(day_can: Can, day_chi: Chi) -> (Chi, Chi) {
    let z = day_chi.index() as i32;
    let c = day_can.index() as i32;
    let a = ((z - c + 10).rem_euclid(12)) as u8;
    let b = ((z - c + 11).rem_euclid(12)) as u8;
    (Chi::from_index(a).unwrap(), Chi::from_index(b).unwrap())
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VuongSuy {
    Vuong, // 旺
    Tuong, // 相
    Huu,   // 休
    Tu,    // 囚
    Tu2,   // 死
}

/// Season of the month branch (rough classical mapping).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Season {
    Xuan, // spring 寅卯
    Ha,   // summer 巳午
    Thu,  // autumn 申酉
    Dong, // winter 亥子
    Tho,  // earth months 辰戌丑未
}

pub fn season_of_chi(z: Chi) -> Season {
    match z {
        Chi::Dan | Chi::Mao => Season::Xuan,
        Chi::Ty2 | Chi::Ngo => Season::Ha,
        Chi::Than | Chi::Dau => Season::Thu,
        Chi::Hoi | Chi::Ty => Season::Dong,
        Chi::Thin | Chi::Tuat | Chi::Suu | Chi::Mui => Season::Tho,
    }
}

/// Phase strength in a season.
pub fn vuong_suy(season: Season, phase: NguHanh) -> VuongSuy {
    // Order: vuong, tuong (generated by vuong), huu (generates vuong), tu (controlled by), tu2 (controls vuong? classical: tu=imprisoned, tu2=dead)
    // For spring (Moc vuong): Moc V, Hoa T, Thuy H, Tho Tu, Kim Tu2
    let order = match season {
        Season::Xuan => [
            NguHanh::Moc,
            NguHanh::Hoa,
            NguHanh::Thuy,
            NguHanh::Tho,
            NguHanh::Kim,
        ],
        Season::Ha => [
            NguHanh::Hoa,
            NguHanh::Tho,
            NguHanh::Moc,
            NguHanh::Kim,
            NguHanh::Thuy,
        ],
        Season::Thu => [
            NguHanh::Kim,
            NguHanh::Thuy,
            NguHanh::Tho,
            NguHanh::Hoa,
            NguHanh::Moc,
        ],
        Season::Dong => [
            NguHanh::Thuy,
            NguHanh::Moc,
            NguHanh::Kim,
            NguHanh::Tho,
            NguHanh::Hoa,
        ],
        Season::Tho => [
            NguHanh::Tho,
            NguHanh::Kim,
            NguHanh::Hoa,
            NguHanh::Thuy,
            NguHanh::Moc,
        ],
    };
    let ranks = [
        VuongSuy::Vuong,
        VuongSuy::Tuong,
        VuongSuy::Huu,
        VuongSuy::Tu,
        VuongSuy::Tu2,
    ];
    for (i, p) in order.iter().enumerate() {
        if *p == phase {
            return ranks[i];
        }
    }
    VuongSuy::Huu
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TruongSinhPhai {
    AmDuong,
    NguHanh,
}

/// 12 stages starting at chang sheng.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TruongSinhStage {
    TruongSinh,
    MocDuc,
    QuanDai,
    LamQuan,
    DeVuong,
    Suy,
    Benh,
    Tu,
    Mo,
    Tuyet,
    Thai,
    Duong,
}

const STAGES: [TruongSinhStage; 12] = [
    TruongSinhStage::TruongSinh,
    TruongSinhStage::MocDuc,
    TruongSinhStage::QuanDai,
    TruongSinhStage::LamQuan,
    TruongSinhStage::DeVuong,
    TruongSinhStage::Suy,
    TruongSinhStage::Benh,
    TruongSinhStage::Tu,
    TruongSinhStage::Mo,
    TruongSinhStage::Tuyet,
    TruongSinhStage::Thai,
    TruongSinhStage::Duong,
];

/// Start branch for am/duong school (yang forward from start, yin backward).
fn am_duong_start(can: Can) -> Chi {
    match can {
        Can::Giap => Chi::Hoi,  // 甲 亥 forward
        Can::At => Chi::Ngo,    // 乙 午 reverse
        Can::Binh => Chi::Dan,  // 丙 寅
        Can::Dinh => Chi::Dau,  // 丁 酉
        Can::Mau => Chi::Dan,   // 戊 like 丙
        Can::Ky => Chi::Dau,    // 己 like 丁
        Can::Canh => Chi::Ty2,  // 庚 巳
        Can::Tan => Chi::Ty,    // 辛 子 reverse
        Can::Nham => Chi::Than, // 壬 申
        Can::Quy => Chi::Mao,   // 癸 卯
    }
}

fn is_yang(can: Can) -> bool {
    can.index().is_multiple_of(2)
}

/// Start for ngu_hanh school by phase of stem.
fn ngu_hanh_start(phase: NguHanh) -> Chi {
    match phase {
        NguHanh::Moc => Chi::Hoi,                  // 木 亥
        NguHanh::Hoa => Chi::Dan,                  // 火 寅
        NguHanh::Kim => Chi::Ty2,                  // 金 巳
        NguHanh::Thuy | NguHanh::Tho => Chi::Than, // 水/土 申
    }
}

/// Stage of `branch` for `stem` under the given school. Caller supplies school (no default).
pub fn truong_sinh_stage(can: Can, branch: Chi, school: TruongSinhPhai) -> TruongSinhStage {
    let (start, forward) = match school {
        TruongSinhPhai::AmDuong => (am_duong_start(can), is_yang(can)),
        TruongSinhPhai::NguHanh => (ngu_hanh_start(ngu_hanh_of_can(can)), true),
    };
    let mut idx = 0i32;
    let mut cur = start.index() as i32;
    let target = branch.index() as i32;
    let step = if forward { 1 } else { -1 };
    while cur != target {
        cur = (cur + step).rem_euclid(12);
        idx += 1;
        if idx >= 12 {
            break;
        }
    }
    STAGES[idx as usize % 12]
}

pub fn phase_of_can(c: Can) -> NguHanh {
    ngu_hanh_of_can(c)
}

pub fn phase_of_chi(z: Chi) -> NguHanh {
    ngu_hanh_of_chi(z)
}
