/** Mirrors CSS custom properties in styles/tokens.css (FR-WEB-001). */
export const tokens = {
  color: {
    ochre: "#F4BA17",
    ochreFocus: "#F4BA17",
    brandAccent: "#F4BA17",
    success: "#2F7D4A",
    danger: "#B42318",
    warning: "#B54708",
    info: "#2C5F8A",
    bg: "#FFFFFF",
    fg: "#1A1A1A",
    muted: "#6B7280",
    border: "#E5E7EB",
    surface: "#F9FAFB",
  },
  space: { 1: "4px", 2: "8px", 3: "12px", 4: "16px", 5: "24px" },
  radius: { sm: "4px", md: "8px", full: "9999px" },
  shadow: { sm: "0 1px 2px rgb(0 0 0 / 0.06)" },
  controlHeight: { xs: "24px", md: "44px" },
  lineHeight: { body: "1.65", control: "1.5" },
} as const;

export const CSS_TOKEN_NAMES = [
  "--color-ochre",
  "--color-ochre-focus",
  "--color-brand-accent",
  "--color-success",
  "--color-danger",
  "--color-warning",
  "--color-info",
  "--color-bg",
  "--color-fg",
  "--color-muted",
  "--color-border",
  "--color-surface",
  "--space-1",
  "--space-2",
  "--space-3",
  "--space-4",
  "--space-5",
  "--radius-sm",
  "--radius-md",
  "--radius-full",
  "--shadow-sm",
  "--control-height-xs",
  "--control-height-md",
  "--line-height-body",
  "--line-height-control",
] as const;
